pipeline {
    agent any
    environment {
        CREATE_SCHEMA = "true"
        DATABASE_URI = credentials("DATABASE_URI")
    }
    stages {
        stage('Setup') {
            steps {
                sh "bash jenkins/setup.sh"
            }
        }
       
        }
    }
}
